export const APPWRITE_CONFIG = {
  ENDPOINT:    process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT    || 'https://sgp.cloud.appwrite.io/v1',
  PROJECT_ID:  process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID  || '',
  DATABASE_ID: process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID || '',
  COLLECTIONS: {
    ENTRIES:      process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_ENTRIES   || '',
    DAY_SUMMARIES:process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_SUMMARIES || '',
    EPISODES:     process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_EPISODES  || '',
    ACTIONS:      process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_ACTIONS   || '',
    TASKS:        process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_TASKS     || '',
  },
  IMAGES_BUCKET_ID: process.env.EXPO_PUBLIC_APPWRITE_BUCKET_IMAGES || '',
  FUNCTIONS: {
    TRANSCRIBE: process.env.EXPO_PUBLIC_APPWRITE_FUNCTION_TRANSCRIBE || '',
  },
};
